version: '3.8'

services:
  dashboard-meteorologico:
    build: .
    container_name: dashboard_papallacta
    ports:
      - "8503:8503"
    volumes:
      # Mapear los datasets para permitir actualizaciones sin reconstruir la imagen
      - ./datasets:/app/datasets:ro
      - ./datasets_limpios:/app/datasets_limpios:ro
    environment:
      - STREAMLIT_SERVER_PORT=8503
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8503/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
